// This file is auto-generated by Payload during build.
// In development, it will be populated when you first run the dev server.
// You can regenerate it with: pnpm payload generate:importmap
export const importMap = {}
